components/About.vue
components/Cover.vue
components/Footer.vue
components/Header.vue
components/Instagram.vue
components/Share.vue
components/Statistics.vue
components/Stories.vue
components/Video.vue
components/ui/Heading.vue
components/ui/Paragraph.vue
components/ui/Subtitle.vue
components/ui/Title.vue
pages/index.vue

Добавила компоненты из архива и шрифты сами тоже подгрузились))

components_and_fonts

---

components/Form.vue
static/button-close.svg

add form-template

---

components/Statistics.vue

mistakes_fixed

---

components/Footer.vue
pages/index.vue

add footer

---

components/Footer.vue
components/Form.vue

Переиспользовал заголовок в форме, убрал лишние стили в форме и футере, убрал лишнюю обёртку в форме

fix form and footer

---

components/Footer.vue

Сделал ширину на весь экран и добавил фоновый цвет

fix footer width and bcg

---

components/Footer.vue
components/Form.vue
components/Header.vue
components/Menu.vue
components/Popup.vue
components/Share.vue
components/ui/Button.vue
components/ui/Paragraph.vue
layouts/default.vue
pages/index.vue

Пофиксил размер шрифта в футере и настроил попап на открытие и закрытие

fix footer font and add popup

---

components/Instagram.vue
components/ui/InstaItem.vue

Инста картинки теперь ссылки и там фотки из массива

instagram-links

---

components/Footer.vue
components/Form.vue
components/ui/Input.vue

Пофиксил недочёты согласно комментариям ревью, создал компонент Input

fix footer and form according to review

---

components/Stories.vue
components/ui/Input.vue

Убрала баг с ошибкой из предыдущего пуллреквеста

input_fixed

---

components/Stories.vue
components/ui/Input.vue

Добавила компоненты в сторис: инпут и кнопку. В компоненте инпута много чего добавилось, там теперь есть пропсы практически для всего: type, placeholder и тп. И даже немного валидации. Инпуту добавила v-model

stories_button_and_input_added

---

components/Form.vue
components/FormContacts.vue
components/FormSocial.vue
components/Popup.vue
components/ui/Input.vue
nuxt.config.js

add adaptive to forms

---

components/Cover.vue
components/Header.vue
components/Video.vue
components/ui/Menu.vue
nuxt.config.js
pages/policy.vue

С хедером пока большой вопрос - пересмотрю как сделать такое скрывающееся меню, пока не имею представления.

Cover, Policy, Video

---

components/Stories.vue
components/ui/Content.vue
components/ui/Pages.vue
components/ui/Story.vue
pages/stories/2.vue
pages/stories/3.vue
pages/stories/4.vue
pages/stories/5.vue
pages/stories/6.vue
pages/stories/7.vue
pages/stories/index.vue
static/polygon.svg
static/polygon__17.svg
static/search.svg

Доделала адаптацию переключения страниц и лупу.

Stories adaptive

---

components/Instagram.vue

add adaptive to instagram

---

components/Statistics.vue
components/ui/Double_Progress-bar.vue
components/ui/Progress-bar.vue

adaptive_stats

---

components/Statistics.vue
pages/index.vue
store/stats.js

Блок статистика теперь берет данные из сервера.

Progress bars data

---

components/Instagram.vue
components/Stories.vue
components/ui/StoriesGrid.vue
components/ui/Story.vue
layouts/default.vue
pages/stories/_id.vue
pages/stories/index.vue
store/instagram.js
store/stories.js

Добавлена подгрузка данных Инстаграмма
Реализован поиск истории

Data Inst and Search

---

components/ui/StoriesGrid.vue
pages/stories/index.vue

Реализован поиск по тексту
Убран pattern
Поиск идёт без учёта регистра

Search fixed

---

pages/stories/_id.vue

**Одобряем :)**
Теперь дата в истории отображается корректно

Fixed date

---

components/Form.vue

adaptive form

---

pages/stories/_id.vue
pages/stories/index.vue

Добавлены заголовки к каждой странице

Added titles on pages

---

README.md
package.json

Added Readme

---

components/Form.vue
components/FormContacts.vue
components/Popup.vue
components/Social.vue
components/ui/FormError.vue

Reverts rak-lechitsya/project#95

Revert "fix popup"

---

components/Form.vue
components/Instagram.vue
components/Share.vue
components/Statistics.vue
components/ui/FormError.vue

Reverts rak-lechitsya/project#93

Revert "Maxx/hotfixed/form validation"

---

components/About.vue
components/Banner.vue
components/Instagram.vue
components/Share.vue
components/Statistics.vue
components/ui/FormError.vue

fix adaptation
